---
title: "member_eda"
author: "Sijian Xuan"
date: "December 4, 2017"
output: html_document
---
load data and libraries
```{r}
library(ggplot2)
library("dplyr")
load("../data/data.all.RData")
```
Member data feature visualization
```{r}
data.all %>%
  ggplot(aes(is_churn, fill = is_churn)) +
  geom_bar() +
  theme(legend.position = "none")
```
```{r}
data.all %>%
   ggplot(aes(`sex(female 2 male 3 NA 1)`, fill = `sex(female 2 male 3 NA 1)`)) +
   geom_bar() +
   theme(legend.position = "none")
```
```{r}
data.all %>%
  ggplot(aes(registervia, fill = registervia)) +
  geom_bar() +
  theme(legend.position = "none") + 
  scale_x_continuous(breaks=seq(0, 13, 1))+
  scale_y_sqrt()
```
```{r}
data.all %>%
  ggplot(aes(city, fill = city)) +
  geom_bar() +
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(0, 25, 1))+
  scale_y_sqrt()

```
```{r}
data.all %>%
  filter(bd > 0 & bd < 80) %>%
  ggplot(aes(bd)) +
  geom_density(fill = "red", bw = 1)
```

Percentage of churn for different gender
```{r}
fema_usr = sum(data.all$`sex(female 2 male 3 NA 1)` == 2) # number of female usr
male_usr = sum(data.all$`sex(female 2 male 3 NA 1)` == 3) # number of male usr
na_usr = sum(data.all$`sex(female 2 male 3 NA 1)` == 1)
fema_usr_churn = sum(data.all$`sex(female 2 male 3 NA 1)` == 2 & data.all$is_churn == 1)
male_usr_churn = sum(data.all$`sex(female 2 male 3 NA 1)` == 3 & data.all$is_churn == 1)
na_usr_churn = sum(data.all$`sex(female 2 male 3 NA 1)` == 1 & data.all$is_churn == 1)

name <- c("female","male","not_specified")
data <- data.frame(name,c(fema_usr_churn/fema_usr,male_usr_churn/male_usr,na_usr_churn/na_usr))
colnames(data) = c("gender","churn_rate")
ggplot(data,aes(x=gender, y = churn_rate)) + geom_bar(stat = "identity", col = "black", fill = "red", width = 0.5)+
  scale_y_continuous(labels = scales::percent)

```
Percenatge of churn with different registration method
```{r}
reg3 = sum(data.all$registervia == 3 & data.all$is_churn == 1)/sum(data.all$registervia == 3)
reg4 = sum(data.all$registervia == 4 & data.all$is_churn == 1)/sum(data.all$registervia == 4)
reg7 = sum(data.all$registervia == 7 & data.all$is_churn == 1)/sum(data.all$registervia == 7)
reg9 = sum(data.all$registervia == 9 & data.all$is_churn == 1)/sum(data.all$registervia == 9)
reg13 = sum(data.all$registervia == 13 & data.all$is_churn == 1)/sum(data.all$registervia == 13)

name <- c("3","4","7","9","13")
data <- data.frame(name,c(reg3,reg4,reg7,reg9,reg13))
colnames(data) = c("registration_method","churn_rate")
ggplot(data,aes(x=registration_method, y = churn_rate)) + geom_bar(stat = "identity", col = "black",fill = "red", width = 0.5)+
  scale_y_continuous(labels = scales::percent)
```
Percenatge of churn with different city
```{r}
city = rep(NA,22)
for (i in 1:22){
  city[i] = sum(data.all$city == i & data.all$is_churn == 1)/sum(data.all$city == i)
}
  
name <- c("1","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22")
data = data.frame(name,c(city[1],city[3],city[4],city[5],city[6],city[7],city[8],city[9],city[10],city[11],city[12],city[13],city[14],city[15],city[16],city[17],city[18],city[19],city[20],city[21],city[22]))
colnames(data) = c("city","churn_rate")
ggplot(data,aes(x=reorder(city, -churn_rate, FUN = max), y = churn_rate)) + geom_bar(stat = "identity", col = "black",fill = "red", width = 1)+
  scale_y_continuous(labels = scales::percent)
```
Age distribution for churn or not
```{r}
dat1 = data.all[data.all$is_churn == 0,]$bd
dat2 = data.all[data.all$is_churn == 1,]$bd
a = rep(0,length(dat1))
b = rep(1,length(dat2))
cc = c(a,b,dat1,dat2)
dat_new=matrix(cc,5000,2)
dat_new = data.frame(dat_new)
dat_new[,1] = as.factor(dat_new[,1])
colnames(dat_new) = c("churn","age")

dat_new %>%
  select(churn,age) %>%
  filter(age > 0 & age < 80) %>%
  ggplot(aes(age, fill = churn)) +
  geom_density(bw = 1, alpha = 0.5) +
  labs(x = "Age - bd")

```